In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df = pd.read_csv('soil_fertility.csv')

In [ ]:
df


In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt


sns.boxplot(df['PH'] )

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# plt.ylim(0,2)
sns.boxplot(df['EC'] )

In [ ]:
threshold = 8.475
deli = np.where(df["PH"]>threshold)
df.drop(deli[0],inplace = True)

t2 = 6.595
delo = np.where(df["PH"] < t2)
df.drop(delo[0],inplace = True)

# noisy_data = df[df["POTASH"] > threshold]

# mean = df["POTASH"].mean()
# df.loc[df["POTASH"] > threshold, "POTASH"] = mean

print(df)

In [ ]:
threshold = 1.25
deli = np.where(df["EC"]>threshold)
df.drop(deli[0],inplace = True)

t2 = 0
delo = np.where(df["EC"] < t2)
df.drop(delo[0],inplace = True)

# noisy_data = df[df["POTASH"] > threshold]

# mean = df["POTASH"].mean()
# df.loc[df["POTASH"] > threshold, "POTASH"] = mean

print(df)

In [ ]:
df.reset_index(inplace=True, drop=True)

In [ ]:
plt.ylim(0,2)
sns.boxplot(df['Organinc Carbon'])

In [ ]:
df.reset_index(inplace=True, drop=True)
threshold = 1.425

deli = np.where(df["Organinc Carbon"]>threshold)
df.drop(deli[0],inplace = True)

t2 = 0.105
delo = np.where(df["Organinc Carbon"] < t2)
df.drop(delo[0],inplace = True)


# print(df)

In [ ]:
df.reset_index(inplace=True, drop=True)

sns.boxplot(df['PHOSPHOROUS'])



In [ ]:
df.reset_index(inplace=True, drop=True)
threshold = 90.80

deli = np.where(df["PHOSPHOROUS"]>threshold)
df.drop(deli[0],inplace = True)

t2 = 0.5
delo = np.where(df["PHOSPHOROUS"] < t2)
df.drop(delo[0],inplace = True)

print(df)

In [ ]:
plt.ylim(0,10)
sns.boxplot(df['POTASH'])

In [ ]:
df.reset_index(inplace=True, drop=True)
threshold = 1178.75

deli = np.where(df["POTASH"]>threshold)
df.drop(deli[0],inplace = True)
t2 = 2
delo = np.where(df["POTASH"] < t2)
df.drop(delo[0],inplace = True)

print(df)

In [ ]:
plt.ylim(0,10)
sns.boxplot(df['CALCIUM_CARBONATE'])

In [ ]:
df.reset_index(inplace=True, drop=True)
threshold = 18.2

deli = np.where(df["CALCIUM_CARBONATE"]>threshold )
df.drop(deli[0],inplace = True)

t2 = 1
delo = np.where(df["CALCIUM_CARBONATE"] < t2)
df.drop(delo[0],inplace = True)

print(df)

In [ ]:
plt.ylim(0,1)
sns.boxplot(df['FERROUS'])

In [ ]:
df.reset_index(inplace=True, drop=True)
threshold = 26

deli = np.where(df["FERROUS"]>threshold)
df.drop(deli[0],inplace = True)
t2 = 0.1
delo = np.where(df["FERROUS"] < t2)
df.drop(delo[0],inplace = True)

print(df)

In [ ]:
plt.ylim(0,1)
sns.boxplot(df['MANAGESE'])

In [ ]:
df.reset_index(inplace=True, drop=True)
threshold = 39.6

deli = np.where(df["MANAGESE"]>threshold)
df.drop(deli[0],inplace = True)
t2 = 0.1
delo = np.where(df["MANAGESE"] < t2)
df.drop(delo[0],inplace = True)

print(df)

In [ ]:
plt.ylim(0,.1)
sns.boxplot(df['ZINK'])

In [ ]:
df.reset_index(inplace=True, drop=True)
threshold = 3.6

deli = np.where(df["ZINK"]>threshold)
df.drop(deli[0],inplace = True)

t2 = 0.01
delo = np.where(df["ZINK"] < t2)
df.drop(delo[0],inplace = True)

print(df)

In [ ]:
plt.ylim(0,0.1)
sns.boxplot(df['COPPER'])

In [ ]:
df.reset_index(inplace=True, drop=True)
threshold = 13.5
deli = np.where(df["COPPER"]>threshold)
df.drop(deli[0],inplace = True)

t2 = 0.02
delo = np.where(df["COPPER"] < t2)
df.drop(delo[0],inplace = True)

print(df)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
cols_to_normalize = ['PH','Organinc Carbon','PHOSPHOROUS','POTASH','CALCIUM_CARBONATE','FERROUS','MANAGESE','ZINK','COPPER','EC']
scaler = MinMaxScaler()
df[cols_to_normalize] = scaler.fit_transform(df[cols_to_normalize])

print(df)


In [ ]:
import numpy as np

criteria = ["PH", "EC", "Organinc Carbon", "PHOSPHOROUS", "POTASH", "CALCIUM_CARBONATE", "FERROUS", "MANAGESE", "ZINK", "COPPER"]
n = len(criteria)

# Initialize an n x n matrix with ones
matrix = np.ones((n, n))

# Assign comparison values directly to the matrix
matrix[0, 1] = 2
matrix[0, 2] = 0.125
matrix[0, 3] = 0.143
matrix[0, 4] = 0.166
matrix[0, 5] = 0.2
matrix[0, 6] = 0.5
matrix[0, 7] = 0.333
matrix[0, 8] = 0.2
matrix[0, 9] = 0.25
matrix[1, 2] = 0.111
matrix[1, 3] = 0.125
matrix[1, 4] = 0.143
matrix[1, 5] = 0.166
matrix[1, 6] = 0.333
matrix[1, 7] = 0.25
matrix[1, 8] = 0.166
matrix[1, 9] = 0.2
matrix[2, 3] = 2
matrix[2, 4] = 3
matrix[2, 5] = 4
matrix[2, 6] = 8
matrix[2, 7] = 7
matrix[2, 8] = 5
matrix[2, 9] = 6
matrix[3, 4] = 2
matrix[3, 5] = 3
matrix[3, 6] = 7
matrix[3, 7] = 6
matrix[3, 8] = 4
matrix[3, 9] = 5
matrix[4, 5] = 2
matrix[4, 6] = 6
matrix[4, 7] = 5
matrix[4, 8] = 3
matrix[4, 9] = 4
matrix[5, 6] = 5
matrix[5, 7] = 4
matrix[5, 8] = 3
matrix[5, 9] = 3
matrix[6, 7] = 0.5
matrix[6, 8] = 0.25
matrix[6, 9] = 0.333
matrix[7, 8] = 0.333
matrix[7, 9] = 0.5
matrix[8, 9] = 2

# Fill in the lower triangle of the matrix using reciprocal values
matrix = matrix + np.tril(1/matrix, -1)

# Normalize the matrix by column
sums = matrix.sum(axis=0)
matrix = matrix / sums

# Print the resulting matrix
print(matrix)



In [ ]:
# sum all columns in each row and divide by the number of criteria
final_weights = np.sum(matrix, axis=1) / len(criteria)

print("criteria weights: ", final_weights)

In [ ]:
Sample=final_weights.sum(axis=0)
print(Sample)

In [ ]:
# Define the decision matrix using the df dataframe
decision_matrix = df[['PH', 'EC', 'Organinc Carbon', 'PHOSPHOROUS', 'POTASH', 'CALCIUM_CARBONATE', 'FERROUS', 'MANAGESE', 'ZINK', 'COPPER']].values  # select only relevant columns

# Define the weights for each criterion from AHP analysis
weights = final_weights

# Expand the weights array to have the same shape as the decision matrix
expanded_weights = np.expand_dims(weights, axis=0)
expanded_weights = np.repeat(expanded_weights, decision_matrix.shape[0], axis=0)

# Calculate the weighted sum for each alternative
weighted_sums = np.sum(decision_matrix * expanded_weights, axis=1)

df['Results'] = weighted_sums
print(df)


In [ ]:
df = df.drop(['SEASON', 'SAMPLE_DATE','FARMER_ENGLISH_NAME','VILLAGE_NAME_ENGLISH','SURVEY_NO','Unnamed: 7','SAMPLE_NO'], axis=1)
print(df)

In [ ]:
df['Quality'] = pd.cut(df.Results,bins=[0,0.25,0.35,0.5,0.7],labels=['Poor','Medium','Good','Excellent'])
# print(df)

test = np.where(df['Results']>0.7)
print (test)

In [ ]:
fig, ax = plt.subplots(figsize =(10,8))
sns.heatmap(df[['EC','Organinc Carbon','PHOSPHOROUS','POTASH','CALCIUM_CARBONATE','FERROUS']].corr(), linewidths= .5)

In [ ]:
temp = df.drop(labels =['Results'], axis = 1)
y = df['Quality']
print (temp)
print(y)
print(y.value_counts())

In [ ]:
x = df.iloc[:,:-1].values
print(x)
y = df.iloc[:,11].values
print(y)

In [ ]:
from sklearn.model_selection import train_test_split


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state=35, shuffle=True)

x_train.shape,x_test.shape




In [ ]:
print(y_test)
print(y_train.value_counts())
print(y_test.value_counts())

In [ ]:
print (y_train)

In [ ]:

x_train.shape,x_test.shape

In [ ]:

y_train.shape,y_test.shape

In [ ]:
from sklearn.feature_selection import VarianceThreshold
# Check if there are any constant features
var_thres = VarianceThreshold(threshold=0)
var_thres.fit(x_train)

In [ ]:
sum(var_thres.get_support())

In [ ]:
# x_test= st_x.transform(x_test) 
print(x_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(max_depth= None, random_state=0)  
classifier.fit(x_train, y_train)

In [ ]:
y_pred= classifier.predict(x_test)
print(y_pred)

In [ ]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred) 

In [ ]:
print(cm)

In [ ]:
from sklearn import metrics

cm = metrics.confusion_matrix(y_test, y_pred)

cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = cm, display_labels = ['Excellent','Good','Medium','Poor'])

cm_display.plot()
plt.show()

# [[659  39   0   0]
#  [ 19 673  22   0]
#  [  0  18 329  18]
#  [  0   1  27 305]]

accuracy = metrics.accuracy_score(y_test, y_pred)
print("Accuracy = ",accuracy)
